{
	"version": 1731964196,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tl_floresta.png",
		"images/spr_heroi-sheet0.png",
		"images/spr_heroi-sheet1.png",
		"images/obj_heroi-sheet0.png",
		"images/obj_colisor-sheet0.png",
		"images/barril-sheet0.png",
		"images/caixagrande-sheet0.png",
		"images/tilemap2.png",
		"images/espinho-sheet0.png",
		"images/obj_bandeira-sheet0.png",
		"images/arco_e_flecha-sheet0.png",
		"images/barra_vida-sheet0.png",
		"images/barra_vida-sheet1.png",
		"images/inimigo_melee_simples-sheet0.png",
		"images/inimigo_ranged-sheet0.png",
		"images/projetil-sheet0.png",
		"images/flecha-sheet0.png",
		"images/flecha-sheet1.png",
		"images/troca_direcao_direita-sheet0.png",
		"images/troca_direcao_esquerda-sheet0.png",
		"images/espinhos_2-sheet0.png",
		"images/espinhos_3-sheet0.png",
		"images/inimigo_melee_intermediario-sheet0.png",
		"images/double_jump-sheet0.png",
		"images/inimigo_melee_chefe-sheet0.png",
		"images/pause_menu-sheet0.png",
		"images/resume_buttom-sheet0.png",
		"images/restart_buttom-sheet0.png",
		"images/exit_buttom-sheet0.png",
		"images/exitpause_buttom-sheet0.png",
		"images/painel_tl.png",
		"images/tilemap.png",
		"images/colisor_para_disparar-sheet0.png",
		"images/pause_buttom-sheet0.png",
		"images/nao_buttom-sheet0.png",
		"images/continue_menu-sheet0.png",
		"images/sim_buttom-sheet0.png",
		"images/sombradialogo-sheet0.png",
		"images/recuperarvida-sheet0.png",
		"images/background_img-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/tilemap5.png",
		"images/novojogo-sheet0.png",
		"images/colisonang2-sheet0.png",
		"images/btn_frente-sheet0.png",
		"images/btn_voltar-sheet0.png",
		"images/btn_atirar-sheet0.png",
		"media/boss battle (candidata a musica do chefe).ogg",
		"media/jungle (usar esse game start).m4a",
		"media/jungle (usar esse game start).ogg",
		"media/swing (candidato a som de flecha).m4a",
		"media/swing (candidato a som de flecha).ogg",
		"media/pulo.m4a",
		"media/pulo.ogg",
		"media/jungle groove grove (usar esse som das fases).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}